apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::665096241917:role/eksctl-roboshop-nodegroup-standard-NodeInstanceRole-bvfFcfPyVGQx
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}

  mapUsers: |
    - groups:
      - roboshop-trainee
      userarn: arn:aws:iam::665096241917:user/jaswanth
      username: jaswanth
    - groups:
      - roboshop-admin
      userarn: arn:aws:iam::665096241917:user/suresh
      username: suresh
    - groups:
      - roboshop-trainee
      userarn: arn:aws:iam::665096241917:user/kavya
      username: kavya
kind: ConfigMap
metadata:
  creationTimestamp: "2026-04-19T02:04:49Z"
  name: aws-auth
  namespace: kube-system
  uid: 065692ae-7557-486a-b0b6-bc8a6d70a93d
